services:
  postgres:
    image: postgres:18
    container_name: football-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: football
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: juancarlosreymedina2002/football-competitions-manager:backend-latest
    container_name: football-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/football?schema=public"
    depends_on:
      - postgres

  frontend:
    image: juancarlosreymedina2002/football-competitions-manager:frontend-latest
    container_name: football-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: